# version: "3.8" // this is ignored so doesn't need to be here
services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "5222:8080"  # Maps host port 5222 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017  # MongoDB connection string
    depends_on:
      - mongodb  # Ensure MongoDB starts before the backend

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"  # Expose MongoDB's default port
    volumes:
      - mongodb_data:/data/db  # Persistent storage for MongoDB

volumes:
  mongodb_data:
